In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [9]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [11]:
## Define the vocabulary size
voc_size = 10000

In [12]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]


In [13]:
one_hot_repr

[[2600, 2685, 369, 4389],
 [2600, 2685, 369, 5139],
 [2600, 8936, 369, 2612],
 [4095, 4404, 8497, 4544, 168],
 [4095, 4404, 8497, 4544, 5651],
 [1646, 2600, 1142, 369, 681],
 [8562, 589, 8099, 4544]]

In [16]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np

In [17]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)

print(embedded_docs)

[[   0    0    0    0 2600 2685  369 4389]
 [   0    0    0    0 2600 2685  369 5139]
 [   0    0    0    0 2600 8936  369 2612]
 [   0    0    0 4095 4404 8497 4544  168]
 [   0    0    0 4095 4404 8497 4544 5651]
 [   0    0    0 1646 2600 1142  369  681]
 [   0    0    0    0 8562  589 8099 4544]]


In [18]:
## Feature representation

dim = 10

In [20]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 111ms/step


array([[[ 0.04753227, -0.03719579,  0.01048491,  0.01646198,
         -0.0181477 ,  0.01143556,  0.00671607,  0.01923175,
         -0.03745089,  0.02760493],
        [ 0.04753227, -0.03719579,  0.01048491,  0.01646198,
         -0.0181477 ,  0.01143556,  0.00671607,  0.01923175,
         -0.03745089,  0.02760493],
        [ 0.04753227, -0.03719579,  0.01048491,  0.01646198,
         -0.0181477 ,  0.01143556,  0.00671607,  0.01923175,
         -0.03745089,  0.02760493],
        [ 0.04753227, -0.03719579,  0.01048491,  0.01646198,
         -0.0181477 ,  0.01143556,  0.00671607,  0.01923175,
         -0.03745089,  0.02760493],
        [-0.00947639,  0.04615856,  0.03909457,  0.04917915,
         -0.00446563, -0.03584998,  0.00575668,  0.00699369,
          0.00775837,  0.03157182],
        [ 0.03161974, -0.04861847, -0.02933737,  0.01823825,
          0.04141134, -0.02983801, -0.02215593, -0.0197566 ,
         -0.03265803,  0.04793947],
        [-0.04682413,  0.01598716,  0.04208704,  0.0

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 2600, 2685,  369, 4389])

In [25]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 81ms/step


array([[ 0.04753227, -0.03719579,  0.01048491,  0.01646198, -0.0181477 ,
         0.01143556,  0.00671607,  0.01923175, -0.03745089,  0.02760493],
       [ 0.04753227, -0.03719579,  0.01048491,  0.01646198, -0.0181477 ,
         0.01143556,  0.00671607,  0.01923175, -0.03745089,  0.02760493],
       [ 0.04753227, -0.03719579,  0.01048491,  0.01646198, -0.0181477 ,
         0.01143556,  0.00671607,  0.01923175, -0.03745089,  0.02760493],
       [ 0.04753227, -0.03719579,  0.01048491,  0.01646198, -0.0181477 ,
         0.01143556,  0.00671607,  0.01923175, -0.03745089,  0.02760493],
       [-0.00947639,  0.04615856,  0.03909457,  0.04917915, -0.00446563,
        -0.03584998,  0.00575668,  0.00699369,  0.00775837,  0.03157182],
       [ 0.03161974, -0.04861847, -0.02933737,  0.01823825,  0.04141134,
        -0.02983801, -0.02215593, -0.0197566 , -0.03265803,  0.04793947],
       [-0.04682413,  0.01598716,  0.04208704,  0.01717171, -0.03848786,
         0.00252367, -0.04064753,  0.00352063